apiVersion: otus.homework/v1
kind: CI
metadata:
  name: test
  namespace: stages
spec:
  tmp_namespace: {{ .Values.tmp_namespace }}
  image_postgres: {{ .Values.image_postgres }}
  image_redis: {{ .Values.image_redis }}
  image_api: {{ .Values.image_api }}
  image_worker: {{ .Values.image_worker }}
  image_nginx: {{ .Values.image_nginx }}
  image_app: {{ .Values.image_app }}